"""add_cascade_delete_to_promocode_activations

Revision ID: 0025
Revises: 0024
Create Date: 2026-01-01 12:16:15.889690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0025'
down_revision: Union[str, None] = '0024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('promocode_activations_promocode_id_fkey'), 'promocode_activations', type_='foreignkey')
    op.create_foreign_key(None, 'promocode_activations', 'promocodes', ['promocode_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'balance',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::bigint"))
    op.drop_constraint(None, 'promocode_activations', type_='foreignkey')
    op.create_foreign_key(op.f('promocode_activations_promocode_id_fkey'), 'promocode_activations', 'promocodes', ['promocode_id'], ['id'])
    # ### end Alembic commands ###